#name: FairCorp CI
#on:
#  push:
#    tags:
#      - v*
#jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: build
# Use the latest version of the Ubuntu image
image: ubuntu:latest

# Use the 'gradle' environment
# This will install Gradle and set it as the default task runner
env:
  - GRADLE_USER_HOME=cache

# This is the list of tasks to run
# These tasks will be run in the order they are listed
tasks:
  # Set up the cache for the Gradle wrapper
  - cache:
      paths:
        - cache/
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}

  # Build the Spring project using Gradle
  - build:
      gradle:
        # Run the 'build' task
        task: build
        # Use the Gradle wrapper
        wrapper: true

  # Run the test suite using Gradle
  - test:
      gradle:
        # Run the 'test' task
        task: test
        # Use the Gradle wrapper
        wrapper: true
